MAGIC_BYTES = b'\xAF\x1B\xB1\xFA'

LOOKUP_TABLE_DEFINITION_OFFSET = 8
LOOKUP_TABLE_SIZE_DEFINITION_OFFSET = 12

STRINGLITERAL_DATA_DEFINITION_OFFSET = 16
STRINGLITERAL_DATA_SIZE_DEFINITION_OFFSET = 20
